### ISSUE TITLE
Call API as registered user, dashboard doesn't render analytics data

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#198] opened 2016-12-29 15:03 UTC
# Steps 
1. Visit https://staging.apinf.io  (version 0.37.0)
2. Sign up 
4. Click on 'APIs' 
5. Select an API 
6. Click on 'Get API key' 
6. Call API 
7. Go to 'Dashboard'  

# Findings   
-  Registered user can go to 'Details' view of any selected API, 'Get API key' and call API successfully but dashboard doesn't render analytics data 
-  Displays message 'No apis that you manage' in dashboard view

**Comment by bajiat** [comment] 2017-01-04 13:59
@saralavanip In what role are you checking the dashboard? If you are a registered user, who is neither admin or API owner, Dashboard is supposed to show "No apis that you manage". The current implementation (by design) only shows information about APIs to owners and admins. There is no data available for other users.

**Comment by saralavanip** [comment] 2017-01-05 06:44
@bajiat , Ok!  Signed in as registered user (neither admin or API owner) , called API  and checked dashboard.

**Comment by bajiat** [comment] 2017-01-09 09:02
Closing the issue.

**Closed** 2017-01-09 09:03 UTC
