### ISSUE TITLE
APIKA: On changing language to Suomi in "Add API" page, related fields and lifecycle statuses don't get translated

### ISSUE THREAD

**Issue by Nazarah** [Digipalvelutehdas/APIKA#322] opened 2017-01-30 12:21 UTC
![image](https://cloud.githubusercontent.com/assets/17976243/22423287/889cb70a-e6f9-11e6-89f9-1fa4e227b41d.png)

![image](https://cloud.githubusercontent.com/assets/17976243/22422918/aeaacfce-e6f7-11e6-8e2f-22f4b0c4943e.png)

**Comment by marla-singer** [comment] 2017-02-01 08:37
@bajiat Verified on nightly.apinf.io. It isn't reproduced. Can be closed
![add-api](https://cloud.githubusercontent.com/assets/20643403/22499964/ba4cd922-e872-11e6-8e95-ed397d3c643d.png)

**Comment by Nazarah** [comment] 2017-02-01 08:39
This is reproducible in APIKA. That's why i reported this. Editing the title to reflect this.

**Comment by bajiat** [comment] 2017-02-01 11:40
@Nazarah Since the fix is in nightly, it will get to the next release. I'm closing the issue now.

**Closed** 2017-02-01 11:40 UTC
Labels: bug
