### ISSUE TITLE
API catalog: click on 'API' in 'Table' view displays 'Page Not Found' error

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#250] opened 2017-01-17 13:39 UTC
# Steps 
1. Visit https://staging.apinf.io (version 0.38.0)   
2. Login as owner   
3. Click on 'APIs' 
4. Go to filter and click on 'Table' tab  
7. Select and click on any API   

# Expected Result  
-  Displays API 'Details' view

# Actual Result 
- Click on any API in 'Table' view displays error : 'Page Not Found'  

# Screenshot   
![click_api_table_view_404error](https://cloud.githubusercontent.com/assets/13309358/22022484/ec9e0b5c-dcca-11e6-9786-0bfbac834543.PNG) 

![click_api_table_view_404_error](https://cloud.githubusercontent.com/assets/13309358/22022530/1374eb10-dccb-11e6-8229-b6019343f767.PNG)

**Comment by marla-singer** [comment] 2017-01-17 13:41
@sara @taija It is already resolved on nightly

**Comment by bajiat** [comment] 2017-01-19 12:44
I also could not reproduce this on nightly. Closing the issue.

**Closed** 2017-01-19 12:44 UTC
Labels: backlog, bug

**Comment by saralavanip** [comment] 2017-01-24 08:10
@bajiat , verified this resolved issue on https://staging.apinf.io version 0.39.0 and it is not reproducible.
