### ISSUE TITLE
Call API as owner , analytics data not rendered in dashboard view

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#189] opened 2016-12-23 15:19 UTC
# Steps 
1. Visit https://staging.apinf.io  (version 0.37.0)
2. Login as owner 
3. Go to Catalog  
4. Click on 'My APIs' 
5. Select an API 
6. Call API as per usage instructions 
7. Go to 'Dashboard'  
8. Select the above API 

# Findings   
- 'Select API' filter lists only 'My APIs'
- Call API as owner , analytics data not rendered in dashboard for successful calls. But shows data for calls that results with 404 error 'Page not found'
- Verified calling API s that are connected to an organization , dashboard renders data for this case as expected.

# Release
 0.37.0 on staging server   

# Screenshot  
![api_notconnected_to_organization](https://cloud.githubusercontent.com/assets/13309358/21456782/4b1a2e28-c933-11e6-9063-565d64a85993.PNG)  

![call_api_no_data_dashboard](https://cloud.githubusercontent.com/assets/13309358/21456800/6dcd29ca-c933-11e6-8a14-743cdb9259bb.PNG)

**Comment by bajiat** [comment] 2017-01-04 14:02
@saralavanip Could you please re-check the dashboard and see if you can see the data now?

**Comment by saralavanip** [comment] 2017-01-05 07:09
@bajiat , re-tested with these steps : login -> add API without connecting to an organization ->call API ->check dashboard. 
Result: data not available

**Comment by bajiat** [comment] 2017-01-09 08:12
@brylie Please try to reproduce

**Comment by bajiat** [comment] 2017-01-11 14:50
@brylie 
I have managed to reproduce. I did not follow the exact steps, logged in as admin user and was calling an API added by someone else, but I assume that should not make a difference.
Made calls today to Test-Books-API using Postman. Checked the dashboard for Test-Books-API, shows only calls made 21 Dec 2016.
I would prefer, if somebody else tried to reproduce as well.

**Comment by bajiat** [comment] 2017-01-13 08:44
@brylie I re-tested the same API: checking dashboard for Test-Books-API in staging.apinf.io.  I can only see the original error message: "No data found. Try changing filtering options..." It does not help if I set the time to 1-31 Dec to see even the calls from 21 Dec 2016.

**Comment by brylie** [comment] 2017-01-13 09:41
I can't duplicate this bug in local development. I have followed the steps to reproduce, and the charts render the analytics data properly.

**Comment by brylie** [comment] 2017-01-13 09:57
This might be a configuration issue in staging.apinf.io:

![screenshot_20170113_115602](https://cloud.githubusercontent.com/assets/17307/21925717/52b267a4-d987-11e6-823b-bb7b090aaf2f.png)

We seem to be using an internal Docker URL, which may not resolve as expected.

**Comment by brylie** [comment] 2017-01-13 10:15
I changed the Proxy settings on staging.apinf.io to match those used in my local development environment:
![screenshot_20170113_121340](https://cloud.githubusercontent.com/assets/17307/21926289/cbaba3e4-d989-11e6-8eea-6390763b3b78.png)

However, the dashboard still fails to fetch the data from Elasticsearch, with the following console messages:

![screenshot_20170113_121302](https://cloud.githubusercontent.com/assets/17307/21926322/edd693ca-d989-11e6-902a-304a7ca40329.png)

**Comment by marla-singer** [comment] 2017-01-13 15:14
@brylie @bajiat I set the right URL for ElasticSearch.  As for me the problem is because of server for staging.apinf.io. If you change proxy from staging.apinf.io:3002 to nightly.apinf.io:3002 then problem won't be repeated

**Comment by bajiat** [comment] 2017-01-19 08:39
Closing the issue as the root cause was found.

**Closed** 2017-01-19 08:40 UTC
Labels: bug, ready
