### ISSUE TITLE
Incorrect number of APIs shown in organization cards 

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#285] opened 2017-01-24 11:24 UTC
# Steps 
1. Visit https://staging.apinf.io (version 0.39.0)   
2. Login as admin   
3. Add Organization
4. Connect APIs to the above organization 
5. Go to 'Organizations' catalog

# Expected Result
-  Number of APIs connected to organizations must be shown correctly in organization card 

#  Actual Result 
 - Currently shows incorrect number of APIs in organization card :  '0' Apis   

# Screenshot 1  
![2apis_connected_org_profile](https://cloud.githubusercontent.com/assets/13309358/22245267/c3e24198-e237-11e6-9a3b-b74e5380e9df.PNG)    

# Screenshot 2  
APIs connected to all organizations, but their number not shown in organization cards. 

![org_catalog](https://cloud.githubusercontent.com/assets/13309358/22245363/2e35efa4-e238-11e6-8cea-f466afb7e5c2.PNG)

**Comment by bajiat** [comment] 2017-01-24 14:37
Duplicate of #240. Closing.

**Closed by bajiat** 2017-01-24 14:37 UTC
Labels: bug, duplicate, enhancement
