### ISSUE TITLE
Change API proxy displays error message

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#268] opened 2017-01-20 11:00 UTC
# Steps  
1. Visit https://staging.apinf.io (version 0.38.1)
2. Login as admin 
3. Go to 'Proxies' 
4. Add multiple proxies and save (eg. staging: API Umbrella, nightly: Nightly Umbrella )
5. Sign out 
6. Sign Up / Sign In as owner 
7. Add API (eg. API 1) with proxy (eg. API Umbrella) and save
8. Go to API view and click on 'Proxy' 
9. Select 'Nightly Umbrella ' from drop down menu 
10. Confirm clicking on 'Change API proxy' button   
11. Edit the form 
12. Click on 'Save&Publish' button

# Expected Result 
Successful in changing API proxy 

# Actual Result 
Displays error message: "Cannot read property 'length' of null"

**Comment by bajiat** [comment] 2017-01-23 08:42
Possible duplicate of  #267

**Comment by marla-singer** [comment] 2017-01-25 10:05
@saralavanip @bajiat The server has correct settings. Please try again. On my side, it works as expected

**Comment by saralavanip** [comment] 2017-01-25 15:10
@bajiat @marla-singer , verified this resolved issue on https://staging.apinf.io v 0.39.0 and it is not reproducible.

**Comment by bajiat** [comment] 2017-01-26 09:28
Closing as resolved.

**Closed by bajiat** 2017-01-26 09:28 UTC
Labels: bug, planning
