### ISSUE TITLE
User unable to add API with other proxy

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#143] opened 2016-12-15 09:34 UTC
# Steps  
1. Visit https://staging.apinf.io 
2. Login as admin 
3. Go to 'Proxies' 
4. Add multiple proxies and save (eg. proxy 1 , proxy 2)
5. Sign out 
6. Sign Up / Sign In as owner 
7. Click on Add API 
8. Fill the  required fields 
9. Select proxy (eg. proxy 2)
10. Fill the required fields  
11. Click on 'Save&Publish' button  

# Expected Result  
User able to add API with other proxy  

# Findings  
- User unable to add API with other proxy 
- Click on 'Save&Publish' not working     

# Screenshot  
![second_proxy_save_not_working](https://cloud.githubusercontent.com/assets/13309358/21218726/5a69c728-c2ba-11e6-8333-f34048d9c209.PNG)

**Comment by bajiat** [comment] 2016-12-19 09:08
@brylie Can you take a look at this?

**Comment by brylie** [comment] 2016-12-19 12:38
@bajiat this may, in part, be due to invalid configuration settings for the second Proxy:

![screenshot_20161219_143701](https://cloud.githubusercontent.com/assets/17307/21313133/b0d42108-c5f8-11e6-9b31-908dd9dab7d2.png)

I.e. what is the status of **nightly-second-umbrella.apinf.io**?

**Comment by saralavanip** [comment] 2016-12-27 09:44
@bajiat , @brylie : testing issue #101 on staging.apinf.io, could we use the 'second proxy' that is stated in above comment or is there any changes?

**Comment by bajiat** [comment] 2017-01-09 08:28
@jykae Can you see if you can reproduce this?

**Comment by bajiat** [comment] 2017-01-23 08:19
Related to #267

**Comment by bajiat** [comment] 2017-01-23 08:20
@marla-singer Can you check this issue as well and see if we can close it as a duplicate for #267?

**Comment by marla-singer** [comment] 2017-01-23 08:30
@bajiat Yes, we can close it as a duplicate

**Comment by bajiat** [comment] 2017-01-23 11:20
Closing as duplicate

**Closed** 2017-01-23 11:20 UTC
Labels: bug, duplicate
