### ISSUE TITLE
Anonymous user can't see any Organization profile

### ISSUE THREAD

**Issue by marla-singer** [Digipalvelutehdas/APIKA#169] opened 2016-12-20 07:36 UTC
Anonymous user can't see any Organization profile, looks like the empty page.
### Steps
1. Go to nightly.apinf.io
2. Sign out if you was sign in
3. Navigate to Organizations Catalog
4. Select any organizations

### Found
Empty page without information about organization

### Expected
Any user can see organization profile

**Comment by bajiat** [comment] 2016-12-20 12:51
@marla-singer Could you add Steps to reproduce, Expected result and Actual result?

**Comment by marla-singer** [comment] 2016-12-21 05:13
@bajiat Done

**Comment by kyyberi** [comment] 2016-12-21 05:25
Confirmed, I get the same result.

**Comment by bajiat** [comment] 2017-01-05 12:30
@brylie Check what is the situation with the issue. Was this fixed in another PR?

**Comment by brylie** [comment] 2017-01-10 10:18
This bug seems to be resolved with the recent re-write of the Organization Profile. Please verify in nightly.

/cc @bajiat

**Comment by bajiat** [comment] 2017-01-17 09:34
Verified in nightly using the steps to reproduce. Result; Anonymous user can view an organization profile. Closing the issue.

**Closed** 2017-01-17 09:34 UTC
Labels: bug, in progress
