### ISSUE TITLE
Connect API with proxy displays error message

### ISSUE THREAD

**Issue by saralavanip** [Digipalvelutehdas/APIKA#267] opened 2017-01-20 10:51 UTC
# Steps  
1. Visit https://staging.apinf.io  (version 0.38.1)
2. Login as admin 
3. Go to 'Proxies' 
4. Add multiple proxies and save (eg. staging: API Umbrella, nightly: Nightly Umbrella )
5. Sign out 
6. Sign Up / Sign In as owner 
7. Add API  
8. Go to API view and click on 'Proxy' 
9. Select  'Nightly Umbrella ' from drop down menu 
10. Fill the form 
11. Click on 'Save&Publish' button   

# Expected Result 
Successful in adding API with proxy 

# Actual Result 
Displays error message: "Cannot read property 'length' of null" 

# Screenshot  
![proxies_staging](https://cloud.githubusercontent.com/assets/13309358/22146964/3fb4a5c6-df0f-11e6-99d6-7f3c572b8faf.PNG)

![connect_api_proxy_error](https://cloud.githubusercontent.com/assets/13309358/22146862/e3191d6a-df0e-11e6-8aff-d240e065c2fc.PNG)

**Comment by marla-singer** [comment] 2017-01-20 14:09
@bajiat I researched this problem. Now we have three proxies:

1. **Staging** - staging.apinf.io:3002
1. **Nightly** - nightly.apinf.io:3002
1. **Second  nightly** - nightly-second-umbrella.apinf.io.apinf.io:3002

Staging.apinf.io and nightly.apinf.io have three proxy settings
### Found result
1. Verified on staging.apinf.io
- API backend can be connected to Staging proxy
- API backend can not be connected to Nightly proxy
- API backend can be connected to Second Nightly proxy 

2. Verified on nightly.apinf.io (the reverse situation)
 - API backend can not be connected to Staging proxy
- API backend can be connected to Nightly proxy
- API backend can be connected to Second Nightly proxy 

3. Verified on local
- API backend can be connected to all proxies

**Comment by bajiat** [comment] 2017-01-23 08:07
@marla-singer Can I assign you to this task, since you have already investigated the issue? Also, this looks like a packaging issue, so maybe you can talk to Shaliko.

**Comment by marla-singer** [comment] 2017-01-23 08:11
@bajiat Yes, you can assign but it's server settings, not code

**Comment by marla-singer** [comment] 2017-01-25 10:04
@saralavanip @bajiat Server has correct settings. Please try again. On my side it works as expected

**Comment by saralavanip** [comment] 2017-01-25 15:08
@bajiat @marla-singer , verified this resolved issue on https://staging.apinf.io v 0.39.0 and it is not reproducible.

**Comment by bajiat** [comment] 2017-01-26 09:26
Verified 
* on staging.apinf.io (v. 0.39.0) by connecting API to nightly Umbrella
* on nightly.apinf.io by connecting API to staging Umbrella
It is not reproducible. Closing as resolved.

**Closed by bajiat** 2017-01-26 09:26 UTC
Labels: bug, planning
